apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-redis-deployment
  labels:
    app: core-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-redis
  template:
    metadata:
      labels:
        app: core-redis
    spec:
      containers:
        - name: core-redis
          image: redis:latest
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: core-redis-service
spec:
  selector:
    app: core-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379