apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-mongodb-deployment
  labels:
    app: core-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-mongodb
  template:
    metadata:
      labels:
        app: core-mongodb
    spec:
      containers:
        - name: core-mongodb
          image: mongo
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: core-mongodb-service
spec:
  selector:
    app: core-mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017