apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-api-deployment
  labels:
    app: core-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-api
  template:
    metadata:
      labels:
        app: core-api
    spec:
      containers:
        - name: core-api
          image: alan1331/core-service-api:1.1.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: core-api-service
spec:
  type: NodePort
  selector:
    app: core-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000