apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-api-deployment
  labels:
    app: mail-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mail-api
  template:
    metadata:
      labels:
        app: mail-api
    spec:
      containers:
        - name: mail-api
          image: alan1331/mail-service-api:1.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: mail-api-service
spec:
  type: NodePort
  selector:
    app: mail-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30001