apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-mongodb-deployment
  labels:
    app: user-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-mongodb
  template:
    metadata:
      labels:
        app: user-mongodb
    spec:
      containers:
        - name: user-mongodb
          image: mongo
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: user-mongodb-service
spec:
  selector:
    app: user-mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017